### ISSUE TITLE
Stratos is configured with too much ram

### ISSUE THREAD

**Issue by tammersaleh** [cloud-gov/cg-deploy-stratos#27]
We're giving each app instance 1.5GB ram, which is only required when the buildpack does the asset compilation. We're compiling in concourse, so we should be fine with much less (~256M?)

**Comment by ccostino** [comment]
We've [reduced the app instance size to `512M` for disk and memory](https://github.com/cloud-gov/cg-deploy-stratos/pull/46) and it seems to be okay.  We'll re-adjust again in the future if need be.
